language: node_js

os:
  - linux
  - osx

node_js:
  - "stable"

script:
  - npm install
  - npm run lint
  - npm run test

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master
